config/routes.rb
Rails.application.routes.draw do
  resources :perks
  resources :projects do
    resources :comments, module: :projects
  end  
  # resources :comments
  # resources :projects
  # root to: 'static_pages#index'
  resource :subscription

  root to: 'projects#index'  
  get   'about', to: 'static_pages#about'
  get   'contact', to: 'static_pages#contact'
  get   'privacy', to: 'static_pages#privacy'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/perk.rb
# == Schema Information
#
# Table name: perks
#
#  id          :integer          not null, primary key
#  amount      :decimal(8, 2)    default(0.0)
#  description :text
#  quantity    :integer
#  title       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  project_id  :integer          not null
#
# Indexes
#
#  index_perks_on_project_id  (project_id)
#
# Foreign Keys
#
#  project_id  (project_id => projects.id)
#
class Perk < ApplicationRecord
  belongs_to :project
end

app/controllers/perks_controller.rb
class PerksController < ApplicationController
  before_action :set_perk, only: %i[ show edit update destroy ]

  # GET /perks or /perks.json
  def index
    @perks = Perk.all
  end

  # GET /perks/1 or /perks/1.json
  def show
  end

  # GET /perks/new
  def new
    @perk = Perk.new
  end

  # GET /perks/1/edit
  def edit
  end

  # POST /perks or /perks.json
  def create
    @perk = Perk.new(perk_params)

    respond_to do |format|
      if @perk.save
        format.html { redirect_to @perk, notice: "Perk was successfully created." }
        format.json { render :show, status: :created, location: @perk }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @perk.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /perks/1 or /perks/1.json
  def update
    respond_to do |format|
      if @perk.update(perk_params)
        format.html { redirect_to @perk, notice: "Perk was successfully updated." }
        format.json { render :show, status: :ok, location: @perk }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @perk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /perks/1 or /perks/1.json
  def destroy
    @perk.destroy

    respond_to do |format|
      format.html { redirect_to perks_path, status: :see_other, notice: "Perk was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_perk
      @perk = Perk.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def perk_params
      params.require(:perk).permit(:title, :amount, :description, :quantity, :project_id)
    end
end

app/helpers/perks_helper.rb
module PerksHelper
end

app/views/perks/_form.html.erb
<%= simple_form_for(@perk) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :amount %>
    <%= f.input :description %>
    <%= f.input :quantity %>
    <%= f.association :project %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/perks/_perk.html.erb
<div id="<%= dom_id perk %>">
  <p>
    <strong>Title:</strong>
    <%= perk.title %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= perk.amount %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= perk.description %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= perk.quantity %>
  </p>

  <p>
    <strong>Project:</strong>
    <%= perk.project_id %>
  </p>

</div>

app/views/perks/edit.html.erb
<h1>Editing perk</h1>

<%= render "form", perk: @perk %>

<br>

<div>
  <%= link_to "Show this perk", @perk %> |
  <%= link_to "Back to perks", perks_path %>
</div>

app/views/perks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Perks</h1>

<div id="perks">
  <% @perks.each do |perk| %>
    <%= render perk %>
    <p>
      <%= link_to "Show this perk", perk %>
    </p>
  <% end %>
</div>

<%= link_to "New perk", new_perk_path %>

app/views/perks/new.html.erb
<h1>New perk</h1>

<%= render "form", perk: @perk %>

<br>

<div>
  <%= link_to "Back to perks", perks_path %>
</div>

app/views/perks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @perk %>

<div>
  <%= link_to "Edit this perk", edit_perk_path(@perk) %> |
  <%= link_to "Back to perks", perks_path %>

  <%= button_to "Destroy this perk", @perk, method: :delete %>
</div>